# Etapa 1: Build de React
FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY frontend/. .
RUN npm run build

# Etapa 2: Servir estáticos con Nginx
FROM nginx:stable-alpine

# Borrar configuración por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copiar tu nginx.conf desde la raíz del proyecto
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copiar el build de React
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
