version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
